# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/
language: c
sudo: required
dist: trusty

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - BOOTSTRAP_LATEX=""
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

install:
  - ./run.sh install_aptget r-cran-car r-cran-reshape2 r-cran-foreach r-cran-plyr
  - ./run.sh install_aptget r-cran-nlme r-cran-e1071 r-cran-earth r-cran-caret
  - ./run.sh install_aptget r-cran-ipred r-cran-kernlab r-cran-rpart r-cran-nnet
  - ./run.sh install_aptget r-cran-mgcv r-cran-mlbench  r-cran-party
  - ./run.sh install_aptget r-cran-pls r-cran-pROC r-cran-randomForest
  - ./run.sh install_aptget r-cran-testthat r-cran-glmnet
  - ./run.sh install_aptget r-cran-ggplot2 r-cran-reshape2 r-cran-data.table
  - ./run.sh install_aptget r-cran-lattice r-cran-devtools r-cran-covr r-cran-lintr

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

after_success:
  - travis_wait Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only: master
